pull_request_rules:
  # approve
  - name: automatic approval
    conditions:
      - author=dsm23
      - check-success=analyze-bundle
      - check-success=check
      - check-success~=codeql \([a-z]*\)
      - check-success=dependency-review
      - check-success=format
      - check-success=gitleaks
      - check-success~=playwright-tests \(\d, \d\)
      - check-success=pr-title
      - check-success=renovate
      - check-success=zizmor
      - "#check-success>=18"
    actions:
      review:
        type: APPROVE
        message: Automatically approving dsm23
  - name: automatic approval for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - check-success=analyze-bundle
      - check-success=check
      - check-success~=codeql \([a-z]*\)
      - check-success=dependency-review
      - check-success=format
      - check-success=gitleaks
      - check-success~=playwright-tests \(\d, \d\)
      - check-success=pr-title
      - check-success=renovate
      - check-success=zizmor
      - "#check-success>=18"
    actions:
      review:
        type: APPROVE
        message: Automatically approving renovate
  # merge
  - name: Automatically merge when GitHub Actions jobs succeed
    conditions:
      - check-success=analyze-bundle
      - check-success=check
      - check-success~=codeql \([a-z]*\)
      - check-success=dependency-review
      - check-success=format
      - check-success=gitleaks
      - check-success~=playwright-tests \(\d, \d\)
      - check-success=pr-title
      - check-success=renovate
      - check-success=zizmor
      - "#check-success>=18"
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  # delete
  - name: automatic deletion of head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
