services:
  mongo:
    image: mongo:latest@sha256:30701f4dbad454b1d847eb55f7eb29527f22aa5f5bcf5fa77e92450620226e07
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
