services:
  mongo:
    image: mongo:latest@sha256:f33feffc6b8f198ce5f257ca8c5e3d7a84e6a4477f9de42da40035cd9f11eeb2
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
