services:
  mongo:
    image: mongo:latest@sha256:fc88459c77982eb464ea5a2c47fccc03a34dbab9bc12b1b864683176a68e3c9a
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
