services:
  mongo:
    image: mongo:latest@sha256:3b8b70989461fe747cc7a14f80dda2462e7e9406d217b6db21d95b4ff772c874
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
