services:
  mongo:
    image: mongo:latest@sha256:412155ba5cdc3674719a516297a7084d33f8a16c54bf32b02b02ccfb6100e8a4
    ports:
      - "27017:27017"
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
